#!/bin/bash
# -----------------------------------------------------------------------------
# Trivadis AG, Infrastructure Managed Services
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# -----------------------------------------------------------------------------
# Name.......: setup_os.sh 
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2018.04.11
# Revision...:  
# Purpose....: Script to download and install latest version of oudbase
# Notes......: The script does download the latest version of OUD Base from
#              GitHub and install it in ${ORACLE_BASE}
# Reference..: --
# License....: Licensed under the Universal Permissive License v 1.0 as 
#              shown at http://oss.oracle.com/licenses/upl.
# -----------------------------------------------------------------------------
# Modified...:
# see git revision history for more information on changes/updates
# -----------------------------------------------------------------------------

# - Customization -----------------------------------------------------------
BOX_NAME ||= "oracle-18c"
# amount of RAM for Vagrant box
BOX_RAM_MB ||= "2048"  
# number of CPUs for Vagrant box
BOX_CPU_COUNT ||= "1"  

# - End of Customization ----------------------------------------------------

# - Vagrant Configuration ---------------------------------------------------

Vagrant.require_version ">= 1.8.0"  
Vagrant.configure("2") do |config|
  config.vm.box = "ol7-latest"
  config.vm.box_url = "https://yum.oracle.com/boxes/oraclelinux/latest/ol7-latest.box"
  config.vm.define BOX_NAME
  
  config.vm.box_check_update = false
  
  # change memory size
  config.vm.provider "virtualbox" do |v|
    v.memory = BOX_RAM_MB
    v.name = BOX_NAME
  end

  # VM hostname
  config.vm.hostname = BOX_NAME

  # Oracle port forwarding
  config.vm.network "forwarded_port", guest: 1521, host: 1521
  config.vm.network "forwarded_port", guest: 5500, host: 5500

  # Provision everything on the first run
  config.vm.provision "shell", path: "scripts/configure_vm.sh", env:
    {
       "ORACLE_ROOT"        => "/u00",
       "ORACLE_DATA"        => "/u01",
       "ORACLE_BASE"        => "/u00/app/oracle",
       "ORACLE_HOME"        => "/u00/app/oracle/product/18.3.0.0",
       "ORACLE_SID"          => "ORCLCDB",
       "ORACLE_CHARACTERSET" => "AL32UTF8",
       "ORACLE_EDITION"      => "EE"
    }

end
# --- EOF -------------------------------------------------------------------